### ISSUE TITLE
Design issues in DeerLab

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#100]
### Minor

- [x] `obir.m` should be integrated into `fitregmodel.m`
- [x] Experiment models depend on time-axis (see #84)
- [ ] Leftovers of `sensitivan.m` should be handled somehow (e.g. #70)
- [ ] Automatically fitted signal scale needs to be communicated somehow to the user
- [x] Lower/Upper boundaries should not be optional inputs but normal ones (as OptToolbox does)

### Major

- [x] Options system. Design of a new system to avoid current onion-like design of options
- [x] Confidence interval interface must be revamped for user simplicity and general functionality (see #90)
- [x] Information structure of builtin models needs improvement
- [x] Functionality overlap between `fitsignal` and `fitmultimodel` (see #107)
- [ ] Model functions: parameter vector as first or second argument? (see #108)
- [x] Distinguish between linear and nonlinear model parameters in multi-parameter models (see #89)
- [ ] Infrastructure of global models and differentiation of global/local parameters (see #82)
- [ ] Distribution models: `rmin` and `rmax` are implicit model parameters (see #62)
